## Task 1

 1.  Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
import sys

def divisionByZero(num):
    '''This fuction divides num by zero and excepts the ZeroDivisionError'''
    try:
        print("The entry is",num)
        r = num/0
    except (ZeroDivisionError):
        print("Oops!", sys.exc_info()[0],"occured.")


divisionByZero(0)

The entry is 0
Oops! <class 'ZeroDivisionError'> occured.


#### 2. 
 
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. <br>
 
subjects=["Americans ","Indians"] <br>
verbs=["play","watch"] <br>
objects=["Baseball","Cricket"]<br> 
 
Output should come as below: <br>
 
Americans  play Baseball.<br>
Americans  play Cricket.<br>
Americans  watch Baseball.<br>
Americans  watch Cricket.<br> 
Indians play Baseball.<br> 
Indians play Cricket.<br> 
Indians watch Baseball.<br> 
Indians watch Cricket.<br>

In [2]:
#List comprehension comes handy here
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

statements=[[a+' '+b+' '+c] for a in subjects for b in verbs for c in objects]
for statement in statements:
    print (''.join(statement))

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2:  
 
 
#### 1.  
 
Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              
increasing is False, the i-th output column is the input vector raised element-wise to the power                
of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre               
    Theophile Vandermonde. 

In [3]:
# numpy reduces much effort in implementing VANDERMORE MATRIX
import numpy as np

x=np.array([1,2,3,4])
N=5
result=[[x**(N-1-i)] for i in range(N)] 

result_matrix=np.asarray(result).T

print('The required Vandermore matrix is : \n {})'.format(result_matrix))


The required Vandermore matrix is : 
 [[[  1   1   1   1   1]]

 [[ 16   8   4   2   1]]

 [[ 81  27   9   3   1]]

 [[256  64  16   4   1]]])
